### ISSUE TITLE
Consider sticking to Scala 3 LTS

### ISSUE THREAD

**Issue by ant8e** [fs2-blobstore/fs2-blobstore#1086]
Hi, recently the Scala 3 version was bumped to 3.4.1, making the library unusable for many Scala 3 projects. Please consider following the recommendation [here](https://www.scala-lang.org/blog/2022/08/17/long-term-compatibility-plans.html#library-maintainers) to stick to LTS versions.

**Comment by gafiatulin** [comment]
@ant8e Thank you for bringing this up and apologies for this. v0.9.14 is coming later today and will be back on LTS.
