### ISSUE TITLE
Putting a file to a directory path when absRoot is set doesn't work (regression)

### ISSUE THREAD

**Issue by DougC** [fs2-blobstore/fs2-blobstore#15]
The implementation of `StfpStore.mkdirs` changed in the 0.6.1 release (https://github.com/fs2-blobstore/fs2-blobstore/commit/042ac302e929aee526401fd46778cc5277a72577) and broke the way directories are created when putting a file to an absolute directory path.

E.g. 
Say you are using a user with a home dir of `/home/user1/` then if you create an SftpStore with an absRoot value of `/foo/bar` and `put` a file using a path of `tmp` it will be correctly placed in `/foo/bar/tmp`.

However, if you attempt to put a file to a path of `baz/tmp` then the store will create a directory called `/home/usr1/home/user1/baz` and then the underlying `ChannelSftp.put` will fail with a `File not found` error.

The problem lies in the `SftpStore.mkdirs` function. It takes `/foo/bar/baz/tmp`, splits it on '/' to get ["", "foo", "bar", "baz", "tmp"], then discards empty strings to get ["foo", "bar", "baz", "tmp"] and starts to build up paths for mkdir as "foo", "foo/bar", and "foo/bar/baz", but loses the leading slash so these all become directories relative the current directory, i.e. the user's home dir.

**Comment by jgogstad** [comment]
Thank you! Fixed in #16 

I'm uncertain of the value of `absRoot` now that `SftpStore` support relative paths. Seems better to just offer the same interface as Jsch. If a client passes `"/foo/bar"` it's absolute, if it passes `foo/bar` it's relative.

**Comment by DougC** [comment]
Thanks!

I agree. I've found it difficult to decide whether to use absRoot and relative paths or just to use absolute paths for the store operations, so it feels like absRoot is somewhat redundant.
