### ISSUE TITLE
SftpStore list hangs when there are too many files in directory

### ISSUE THREAD

**Issue by hygorkn** [fs2-blobstore/fs2-blobstore#413]
I'm developing a process to list for changes in a SFTP server and download the new files.

However, when there are too many files in a directory, the `list` method hangs.

```scala
val store = SftpStore(sftpConnection, Some(32))
```

```scala
  val x = store
    .allocated
    .map(_._1)
    .unsafeRunSync()
    .list(Path(hugeFolder))
    .take(10)
    .compile
    .toList
    .unsafeRunSync()

  println(x) // Never reaches here
```

```scala
  val y = store.use { client =>
    client
      .list(Path(hugeFolder))
      .take(10)
      .compile
      .toList
  }.unsafeRunSync()

  println(y) // Never reaches here
```

```scala
  val z = Stream
    .resource(store)
    .flatMap(f => f.list(Path(hugeFolder)))
    .take(10)
    .compile
    .toList
    .unsafeRunSync()

  println(z) // Never reaches here
```

The `hugeFolder` dir contains arround 7k files. If I change it to a small directory (10 files) the code works fine.

These are the dependencies:

```scala
  def ivyDeps = Agg(
    ivy"co.fs2::fs2-core:3.0.4",
    ivy"co.fs2::fs2-io:3.0.4",
    ivy"org.typelevel::cats-effect:3.1.0",
    ivy"com.github.fs2-blobstore::core:0.9.0-beta3",
    ivy"com.github.fs2-blobstore::sftp:0.9.0-beta3"
  )
```

Thanks.

**Comment by gafiatulin** [comment]
Thank you for reporting. It probably doesn't matter much, but do you know which SFTP server is used on the other side?

**Comment by hygorkn** [comment]
The server is running OpenSSH_4.3

**Comment by gafiatulin** [comment]
@hygorkn 
Sorry for such a delayed response. 

Can you please provide your app (do you use IOApp or something else) and SFTP session setups, rough estimate on file sizes in SFTP, and number of cores/memory in the environment where your app is running. 

I tried to replicate the issue and was not able to: [blobstore-sftp-test](https://github.com/gafiatulin/blobstore-sftp-test). Here it is listing 50k files: https://github.com/gafiatulin/blobstore-sftp-test/runs/2763544039?check_suite_focus=true#step:5:17

**Comment by hygorkn** [comment]
Hi @gafiatulin,

I was trying to mock up a stream processing to see if I could replace an Akka Streams service that I have, so I wrote a simple fs2 script using ```import cats.effect.unsafe.implicits.global```.

To test I was trying to download, gunzip and parse 7500 xml.gz files, totalizing ~500mb. 

But after checking the test you wrote, I tried removing the implicits and using ```IOApp``` instead. After that!

Here is what the code looked like:

```scala
  val session: IO[Session] = IO {
    val jsch = new JSch()
    val session = jsch.getSession("sftp-user", "sftp-host", 22)
    val proxy = new ProxySOCKS5("proxy-host", 1080)

    proxy.setUserPasswd("proxy-user", "proxy-password")

    session.setConfig("StrictHostKeyChecking", "no")
    session.setPassword("sftp-password")
    session.setTimeout(60 * 60)
    session.setProxy(proxy);

    session
  }

  val store: Resource[IO, SftpStore[IO]] = SftpStore(session, Some(32))
  val pmFolder = "/some/huge/directory"

  def main(args: List[String]): Unit = {
    val xs = fs2.Stream
      .resource(store)
      .flatMap(_.list(Path(pmFolder), true))
      .evalMap(file => store.use { _.get(file, 1024).compile.toList  })
      .flatMap(fs2.Stream.emits)
      .through(fs2.compression.Compression[IO].gunzip(1024))
      .flatMap(_.content)
      .through(fs2.io.toInputStream)
      .map(file => parse(IOUtils.toString(file)))
      .debug()
      .compile
      .toList()

    println(xs.length)
  }
```

Thanks for your support!

**Comment by gafiatulin** [comment]
@hygorkn Is it still blocking after you replaced `cats.effect.unsafe.implicits.global` with IOApp?

**Comment by hygorkn** [comment]
No, it is working normally.

**Comment by gafiatulin** [comment]
Great! I'm going to close the issue then. 

Couple notes regarding code from this comment: https://github.com/fs2-blobstore/fs2-blobstore/issues/413#issuecomment-857828552: 
1. You probably want to reuse the same store instance you used for listing to get the data as well. 
2. It doesn't really make sense to compile `Stream[O, Byte]` to `List[Byte]` and then unwrap resulting list using `Stream.emits` back to be `Stream[O, Byte]`
3. Can use `through(fs2.text.utf8Decode).compile.foldMonoid` instead of going through InputStream and, I assume, `org.apache.commons.io.IOUtils` to get string content from byte stream.

Maybe something like this:

```scala
val session: IO[Session] = IO.delay {
  val jsch = new JSch()
  val session = jsch.getSession("user", "localhost", 2222)
  session.setTimeout(10000)
  session.setPassword("password")
  val config = new Properties
  config.put("StrictHostKeyChecking", "no")
  session.setConfig(config)
  session
}

val store: Resource[IO, SftpStore[IO]] = SftpStore(session, Some(32))
val pmFolder = "/some/huge/directory"

// Not sure what is this
type T = ???
def parse(str: String): T = ???
// Not sure what is this

def listContents(
    sftpStore: SftpStore[IO],
    folderPath: Path.Plain
): IO[List[T]] =
  sftpStore
    .list(folderPath, recursive = true)
    .evalMap { file => // Can also use parEvalMap/parEvalMapUnordered
      val fileContent: IO[String] = sftpStore
        .get(file, 1024)
        .through(Compression[IO].gunzip(1024))
        .flatMap(_.content)
        .through(fs2.text.utf8Decode)
        .compile
        .foldMonoid

      fileContent.map(parse)
    }
    .debug()
    .compile
    .toList

override def run(args: List[String]): IO[ExitCode] = store
  .use { sftpStore =>
    for {
      l <- listContents(sftpStore, Path(pmFolder))
      _ <- Console[IO].println(l.length)
    } yield ()
  }
  .as(ExitCode.Success)
```

**Comment by hygorkn** [comment]
In the current solution, the parser is the bottleneck of the stream. So I separated the download and parse pipes so I can control how many threads each one uses. Something like:

 ```parEvalMap(4)(download).parEvalMap(24)(parse)```

I'll try to apply you suggestions and see how it performs.

Thank you very much!
