### ISSUE TITLE
Support for Multipart Uploads for content of a known size in S3Store

### ISSUE THREAD

**Issue by MattDaveyI** [fs2-blobstore/fs2-blobstore#424]
Hi,

For reference, I've been using the following artefacts for this example:

```
"com.github.fs2-blobstore" %% "core" % "0.7.3",
"com.github.fs2-blobstore" %% "s3"   % "0.7.3"
```

Apologies if this is already covered somewhere.  I've been playing around with the S3Store a bit and it seems that it's only possible to initiate a multipart upload for an object when directed down the `putUnknownSize` branch.  It's possible that I'm just doing something odd, as this is my first real exposure to fs2 and the V2 AWS Java SDK, so as a crude example:

```scala
import blobstore.Path
import blobstore.s3.S3Store
import cats.effect.{ExitCode, IO, IOApp, Resource}
import fs2.{Chunk, Stream}
import software.amazon.awssdk.auth.credentials.{AwsSessionCredentials, StaticCredentialsProvider}
import software.amazon.awssdk.regions.Region
import software.amazon.awssdk.services.s3.S3AsyncClient

import scala.util.Random

object TestApp extends IOApp {

  private val GB = 1024L * 1024L * 1024L
  private val ObjectSize = (5L * GB) + 1L

  private val myBucket: String = ??? // TODO - fill in
  private val myKey: String = ??? // TODO - fill in
  private val myRegion: Region = ??? // TODO - fill in

  override def run(args: List[String]): IO[ExitCode] =
    s3AsyncClientResource
      .flatMap(s3Client => Resource.liftF(S3Store[IO](s3Client, None, None)))
      .use { s3Store =>
        fileInputStream
//          .through(s3Store.put(Path(s"s3://$myBucket/$myKey")))
          .through(s3Store.put(Path(s"s3://$myBucket/$myKey").withSize(Some(ObjectSize))))
          .compile
          .drain
      }
      .as(ExitCode.Success)

  private def s3AsyncClientResource: Resource[IO, S3AsyncClient] =
    Resource.fromAutoCloseable(IO(S3AsyncClient.builder().region(myRegion).build()))

  // Just some random bytes, I don't really care for the purposes of this example
  private def fileInputStream: Stream[IO, Byte] =
    Stream.constant[IO, Unit](())
      .flatMap(_ => Stream.eval(IO(Random.nextBytes(1024))))
      .flatMap(bytes => Stream.chunk(Chunk.bytes(bytes)))
      .take(ObjectSize)

}
```

This currently fails when trying to upload to S3 with an S3 error with the message `Your proposed upload exceeds the maximum allowed size`.  If I change the `through` to `.through(s3Store.put(Path(s"s3://$myBucket/$myKey")))` (i.e. we no longer specify the object size) then the multipart upload starts as expected.

Would be possible to add support for MPUs with a known content size?  Ideally as a part of this it would also be possible to avoid buffering the entirety of each part into memory for each UploadPartRequest - we'll know the total size of the object and how many bytes we've currently processed so I think that we could work out the size of the upcoming part and hopefully do something similar to the request in `putKnownSize` (which doesn't seem to require buffering the entire object into memory).  This is less of a problem with smaller objects (since we can use a smaller buffer size), but with objects near the S3 object limit (5TB) we are limited to 10,000 parts so must use a large buffer size (e.g. 500 MB), which is a significant extra overhead.

**Comment by gafiatulin** [comment]
Yes, we should support MPU with known size, it is actually [recommended](https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html) to use MPUs for files > 100MB.

**Comment by gafiatulin** [comment]
It might be a bit tricky with how it is implemented at the moment, but it should be possible to not require large buffers 👍

**Comment by gafiatulin** [comment]
@MattDaveyI FYI #435

**Comment by gafiatulin** [comment]
I see that you are using version with Cats-Effect 2.x/FS2 2.x, after this is merged I'll backport this and some other changes to CE2.

**Comment by MattDaveyI** [comment]
Fantastic, thanks a lot!
