### ISSUE TITLE
Java 8 Support

### ISSUE THREAD

**Issue by bpholt** [fs2-blobstore/fs2-blobstore#469]
With `v0.8.3`, my application throws `java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer` when using `S3Store` on Java 8. Has Java 8 support been dropped?

**Comment by gafiatulin** [comment]
`ByteBuffer.clear` should be available on Java 8 as well, with clear implementation coming from `java.nio.Buffer`. 
Probably the problem is with us using Java 11 when producing jars. Maybe we can use Java 8 for building jars.

**Comment by gafiatulin** [comment]
Should be fixed in #481 
I'll release v0.8.4 with change backported, would be nice if you could check if that works.

**Comment by gafiatulin** [comment]
0.8.4 is released now, should be available shortly.

**Comment by gafiatulin** [comment]
@bpholt please reopen the issue if you are still experiencing problems with running on Java 8 using v0.8.4.
