### ISSUE TITLE
README is still based on v0.7.x

### ISSUE THREAD

**Issue by DougC** [fs2-blobstore/fs2-blobstore#630]
The code examples I've tried no longer work in v0.9.x

**Comment by gafiatulin** [comment]
@jgogstad I see https://github.com/jgogstad/fs2-blobstore/tree/microsite has relatively recent changes (Dec 2021). Is it the latest iteration of microsite work?

**Comment by gafiatulin** [comment]
I'll try to find some time to work on this hopefully in not too distant future.

**Comment by jgogstad** [comment]
Yeah, I intended to have this done a long time ago. Only thing remaining is getting publish-on-release working. Could do that in two steps I guess. 

Let me look over the microsite and we can publish that and GHA integration in two steps.
