### ISSUE TITLE
`S3Store.stat` always returns a Url even if the key doesn't exist in the s3 bucket

### ISSUE THREAD

**Issue by DougC** [fs2-blobstore/fs2-blobstore#777]
https://github.com/fs2-blobstore/fs2-blobstore/blob/34eeb7ad34daadd421eee7e25ccb15c75f78e66c/s3/src/main/scala/blobstore/s3/S3Store.scala#L434

Documentation on `Store.stat` is a little lacking, but my understanding is that it should return a stream with a single url if the object exists in the store, and an empty stream if the object does not exist, so that it's possible to determine if an object is in the store before trying to, say, `get` it.

The implementation of `S3Store.stat` always returns a stream containing a single url, even if the key does not exist in s3.

**Comment by gafiatulin** [comment]
@DougC thank you for raising the issue, v0.8.7 and v0.9.7 have been released.

**Comment by DougC** [comment]
That's brilliant! Thanks very much for your work on this library.
